const cameras = [
    {
        "id": 0,
        "name": "I-71 at I-75",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/CCTV035a-L.jpg",
        "city": "Cincinnati",
        "rushHourPriority": true,
    },
    {
        "id": 1,
        "name": "I-75 at 3rd St",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/CCTV022.jpg",
        "city": "Cincinnati",
        "rushHourPriority": true,
    },
    {
        "id": 2,
        "name": "I-71 at Gilbert Ave",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/CCTV_I-71-Gilbert.jpg",
        "city": "Cincinnati",
        "rushHourPriority": true,
    },
    {
        "id": 3,
        "name": "I-471 SB just S of Ky Rt 8",
        "url": "http://www.trimarc.org/images/milestone/CCTV_06_471_0045.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 4,
        "name": "I-75 at North of Mitchell Ave",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/CCTV014a.jpg",
        "city": "Cincinnati",
        "rushHourPriority": true,
    },
    {
        "id": 5,
        "name": "I-75 at SR-562 (Norwood Lateral)",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/I-75_at_SR-562.jpg",
        "city": "Cincinnati",
        "rushHourPriority": true,
    },
    {
        "id": 6,
        "name": "I-75 SB at N of Galbraith Rd",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/CCTV008a-L.jpg",
        "city": "Cincinnati",
        "rushHourPriority": true,
    },
    {
        "id": 7,
        "name": "I-75 at N of Union Centre Blvd",
        "url": "https://itscameras.dot.state.oh.us/images/cincinnati/I-75_at_Union_Centre_Blvd.jpg",
        "city": "Cincinnati",
        "rushHourPriority": true,
    },
    {
        "id": 8,
        "name": "I-71 at SR-562 (Norwood Lateral)",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/CCTV079a.jpg",
        "city": "Cincinnati",
        "rushHourPriority": true,
    },
    {
        "id": 9,
        "name": "I-71 at I-471 (Van Meter St)",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/CCTV037a.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 10,
        "name": "I-71 at McGregor Ave",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/CCTV087a.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 11,
        "name": "I-74 at Montana Ave",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/CCTV142.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 12,
        "name": "I-275 at East of Kellogg Ave",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/CCTV4110-5.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 13,
        "name": "I-71 at Montgomery Rd (Kenwood)",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/CCTV074a.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 14,
        "name": "Colerain Ave at Springdale Rd",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/Colerain_Ave_at_Springdale.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 15,
        "name": "I-71/I-75 at N of Buttermilk Pike",
        "url": "http://www.trimarc.org/images/milestone/CCTV_06_75_1868.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 16,
        "name": "I-75 at N of Hopple St",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/I-75_N_of_Hopple.jpg",
        "city": "Cincinnati",
        "rushHourPriority": true,
    },
    {
        "id": 17,
        "name": "I-75 at N of Paddock Rd",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/CCTV010a-L.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 18,
        "name": "SR-126 at E of Plainfield Rd",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/CCTV4159.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 19,
        "name": "I-75 SB Butler county rest area",
        "url": "https://itscameras.dot.state.oh.us/images/rest_area/I-75_Butler_SB.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 20,
        "name": "I-71 at SR-741/Kings Mills Rd",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/CCTV092a.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 21,
        "name": "Mason Montgomery Rd & Parkway Dr",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/FEMM167.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 22,
        "name": "I-71 at Deerfield Rd",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/CCTV071a.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 23,
        "name": "I-71 at Red Bank Rd",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/CCTV077a-L.jpg",
        "city": "Cincinnati",
        "rushHourPriority": true,
    },
    {
        "id": 24,
        "name": "I-71 at Montgomery Rd",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/CCTV083a.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 25,
        "name": "SR-125 at Five Mile Rd, Looking South",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/SR-125_Five_Mile_South.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 26,
        "name": "I-275 at Barg Salt Run Rd",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/CCTV4153.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 27,
        "name": "Colerain Ave at SR-126 WB Ramp",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/Colerain_Ave_at_SR-126_WB.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 28,
        "name": "I-275 at US-50 Underpass (E of OH/IN Line)",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/CCTV062.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 29,
        "name": "I-71/I-75 at Burlington Pike",
        "url": "http://www.trimarc.org/images/milestone/CCTV_06_75_1812.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 30,
        "name": "I-71/I-75 at 12th St",
        "url": "http://www.trimarc.org/images/milestone/CCTV_06_75_1908.jpg",
        "city": "Cincinnati",
        "rushHourPriority": true,
    },
    {
        "id": 31,
        "name": "I-71/I-75 N on Brent Spence Bridge",
        "url": "http://www.trimarc.org/images/milestone/CCTV_06_75_1911.jpg",
        "city": "Cincinnati",
        "rushHourPriority": true,
    },
    {
        "id": 32,
        "name": "I-71 at Dana Ave",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/CCTV082a.jpg",
        "city": "Cincinnati",
        "rushHourPriority": true,
    },
    {
        "id": 33,
        "name": "I-74 at North Bend Rd",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/CCTV144.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 34,
        "name": "I-74 at Harrison Ave",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/CCTV147.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 35,
        "name": "I-275 at US-42",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/CCTV001a-L.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 36,
        "name": "I-71 at US-50 (Lyte Tunnel)",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/CCTV042a.jpg",
        "city": "Cincinnati",
        "rushHourPriority": true,
    },
    {
        "id": 37,
        "name": "I-275 at SR-125",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/CCTV4152.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 38,
        "name": "I-71/I-75 north of Richwood Rd",
        "url": "http://www.trimarc.org/images/milestone/CCTV_06_75_1758.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 39,
        "name": "I-275 East of Turkeyfoot Road Mile 81.2",
        "url": "http://www.trimarc.org/images/milestone/CCTV_06_275_0812.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 40,
        "name": "I-275 East of Johns Hill Road",
        "url": "http://www.trimarc.org/images/milestone/CCTV_06_275_0762.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 41,
        "name": "I-275 at US-27 Overpass",
        "url": "http://www.trimarc.org/images/milestone/CCTV_06_275_0741.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 42,
        "name": "I-471 SB at Highland Ave Overpass",
        "url": "http://www.trimarc.org/images/milestone/CCTV_06_471_0023.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 43,
        "name": "I-71 at Robertson Ave",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/CCTV080a.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 44,
        "name": "I-71 at Euclid Ave",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/CCTV4075.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 45,
        "name": "SR-126 at I-71 SB Ramp",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/CCTV073_Signal.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
];

module.exports = cameras;