const cameras = [
    {
        "id": 0,
        "name": "I-71 at I-75",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/CCTV035a-L.jpg",
        "city": "Cincinnati",
        "rushHourPriority": true,
    },
    {
        "id": 1,
        "name": "I-75 at 3rd St",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/CCTV022.jpg",
        "city": "Cincinnati",
        "rushHourPriority": true,
    },
    {
        "id": 2,
        "name": "I-71 at Gilbert Ave",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/CCTV_I-71-Gilbert.jpg",
        "city": "Cincinnati",
        "rushHourPriority": true,
    },
    {
        "id": 3,
        "name": "I-471 SB just S of Ky Rt 8",
        "url": "http://www.trimarc.org/images/milestone/CCTV_06_471_0045.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 4,
        "name": "I-75 at North of Mitchell Ave",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/CCTV014a.jpg",
        "city": "Cincinnati",
        "rushHourPriority": true,
    },
    {
        "id": 5,
        "name": "I-75 at SR-562 (Norwood Lateral)",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/I-75_at_SR-562.jpg",
        "city": "Cincinnati",
        "rushHourPriority": true,
    },
    {
        "id": 6,
        "name": "I-75 SB at N of Galbraith Rd",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/CCTV008a-L.jpg",
        "city": "Cincinnati",
        "rushHourPriority": true,
    },
    {
        "id": 7,
        "name": "I-75 at N of Union Centre Blvd",
        "url": "https://itscameras.dot.state.oh.us/images/cincinnati/I-75_at_Union_Centre_Blvd.jpg",
        "city": "Cincinnati",
        "rushHourPriority": true,
    },
    {
        "id": 8,
        "name": "I-71 at SR-562 (Norwood Lateral)",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/CCTV079a.jpg",
        "city": "Cincinnati",
        "rushHourPriority": true,
    },
    {
        "id": 9,
        "name": "I-71 at I-471 (Van Meter St)",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/CCTV037a.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 10,
        "name": "I-71 at McGregor Ave",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/CCTV087a.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 11,
        "name": "I-74 at Montana Ave",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/CCTV142.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 12,
        "name": "I-275 at East of Kellogg Ave",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/CCTV4110-5.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 13,
        "name": "I-71 at Montgomery Rd (Kenwood)",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/CCTV074a.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 14,
        "name": "Colerain Ave at Springdale Rd",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/Colerain_Ave_at_Springdale.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 15,
        "name": "I-71/I-75 at N of Buttermilk Pike",
        "url": "http://www.trimarc.org/images/milestone/CCTV_06_75_1868.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 16,
        "name": "I-75 at N of Hopple St",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/I-75_N_of_Hopple.jpg",
        "city": "Cincinnati",
        "rushHourPriority": true,
    },
    {
        "id": 17,
        "name": "I-75 at N of Paddock Rd",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/CCTV010a-L.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 18,
        "name": "SR-126 at E of Plainfield Rd",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/CCTV4159.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 19,
        "name": "I-75 SB Butler county rest area",
        "url": "https://itscameras.dot.state.oh.us/images/rest_area/I-75_Butler_SB.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 20,
        "name": "I-71 at SR-741/Kings Mills Rd",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/CCTV092a.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 21,
        "name": "Mason Montgomery Rd & Parkway Dr",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/FEMM167.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 22,
        "name": "I-71 at Deerfield Rd",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/CCTV071a.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 23,
        "name": "I-71 at Red Bank Rd",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/CCTV077a-L.jpg",
        "city": "Cincinnati",
        "rushHourPriority": true,
    },
    {
        "id": 24,
        "name": "I-71 at Montgomery Rd",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/CCTV083a.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 25,
        "name": "SR-125 at Five Mile Rd, Looking South",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/SR-125_Five_Mile_South.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 26,
        "name": "I-275 at Barg Salt Run Rd",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/CCTV4153.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 27,
        "name": "Colerain Ave at SR-126 WB Ramp",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/Colerain_Ave_at_SR-126_WB.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 28,
        "name": "I-275 at US-50 Underpass (E of OH/IN Line)",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/CCTV062.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 29,
        "name": "I-71/I-75 at Burlington Pike",
        "url": "http://www.trimarc.org/images/milestone/CCTV_06_75_1812.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 30,
        "name": "I-71/I-75 at 12th St",
        "url": "http://www.trimarc.org/images/milestone/CCTV_06_75_1908.jpg",
        "city": "Cincinnati",
        "rushHourPriority": true,
    },
    {
        "id": 31,
        "name": "I-71/I-75 N on Brent Spence Bridge",
        "url": "http://www.trimarc.org/images/milestone/CCTV_06_75_1911.jpg",
        "city": "Cincinnati",
        "rushHourPriority": true,
    },
    {
        "id": 32,
        "name": "I-71 at Dana Ave",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/CCTV082a.jpg",
        "city": "Cincinnati",
        "rushHourPriority": true,
    },
    {
        "id": 33,
        "name": "I-74 at North Bend Rd",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/CCTV144.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 34,
        "name": "I-74 at Harrison Ave",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/CCTV147.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 35,
        "name": "I-275 at US-42",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/CCTV001a-L.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 36,
        "name": "I-71 at US-50 (Lyte Tunnel)",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/CCTV042a.jpg",
        "city": "Cincinnati",
        "rushHourPriority": true,
    },
    {
        "id": 37,
        "name": "I-275 at SR-125",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/CCTV4152.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 38,
        "name": "I-71/I-75 north of Richwood Rd",
        "url": "http://www.trimarc.org/images/milestone/CCTV_06_75_1758.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 39,
        "name": "I-275 East of Turkeyfoot Road Mile 81.2",
        "url": "http://www.trimarc.org/images/milestone/CCTV_06_275_0812.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 40,
        "name": "I-275 East of Johns Hill Road",
        "url": "http://www.trimarc.org/images/milestone/CCTV_06_275_0762.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 41,
        "name": "I-275 at US-27 Overpass",
        "url": "http://www.trimarc.org/images/milestone/CCTV_06_275_0741.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 42,
        "name": "I-471 SB at Highland Ave Overpass",
        "url": "http://www.trimarc.org/images/milestone/CCTV_06_471_0023.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 43,
        "name": "I-71 at Robertson Ave",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/CCTV080a.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 44,
        "name": "I-71 at Euclid Ave",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/CCTV4075.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 45,
        "name": "SR-126 at I-71 SB Ramp",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/CCTV073_Signal.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 46,
        "name": "I-75 at Mitchell Ave",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/CCTV015a.jpg",
        "city": "Cincinnati",
        "rushHourPriority": true,
    },
    {
        "id": 47,
        "name": "I-275 at US-52",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/CCTV4111.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 48,
        "name": "I-75 at Western Hills Viaduct",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/CCTV019a-L.jpg",
        "city": "Cincinnati",
        "rushHourPriority": true,
    },
    {
        "id": 49,
        "name": "I-75 at S of Hopple St",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/I-75_S_of_Hopple.jpg",
        "city": "Cincinnati",
        "rushHourPriority": true,
    },
    {
        "id": 50,
        "name": "I-75 at N of I-74",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/CCTV016a.jpg",
        "city": "Cincinnati",
        "rushHourPriority": true,
    },
    {
        "id": 51,
        "name": "I-75 at Mitchell Ave",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/CCTV015a.jpg",
        "city": "Cincinnati",
        "rushHourPriority": true,
    },
    {
        "id": 52,
        "name": "I-75 at Vine St",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/I-75_at_Vine_St.jpg",
        "city": "Cincinnati",
        "rushHourPriority": true,
    },
    {
        "id": 53,
        "name": "I-75 NB at Davis St",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/CCTV007a-L.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 54,
        "name": "I-75 at Cin-Day Rd",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/CCTV068a.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 55,
        "name": "I-71 at Jeremiah Morrow Bridge",
        "url": "https://itscameras.dot.state.oh.us/images/cincinnati/I-71_at_Jeremiah_Morrow_Bridge.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 56,
        "name": "I-71 at SR-48",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/CCTV4155.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 57,
        "name": "I-71/I-75 at I-275",
        "url": "http://www.trimarc.org/images/milestone/CCTV_06_75_1847.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 58,
        "name": "I-71 at Smith Rd",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/CCTV081a.jpg",
        "city": "Cincinnati",
        "rushHourPriority": true,
    },
    {
        "id": 59,
        "name": "I-275 at US-50, Exit 16, Indiana",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/CCTV063.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 60,
        "name": "I-71 at North of Stewart Rd",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/CCTV076a.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 61,
        "name": "I-71 at SR-126 (RRCC)",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/CCTV073a-L.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 62,
        "name": "I-71 at Pfeiffer Rd",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/CCTV072a-L.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 63,
        "name": "I-71 at N of Snider Rd",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/CCTV4158.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 64,
        "name": "I-75 at Sharon Rd",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/CCTV004a-L.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 65,
        "name": "I-275 at SR-747",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/CCTV003a.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 66,
        "name": "I-74 East of Harrison Ave",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/CCTV146.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 67,
        "name": "I-74 at Elmore St",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/CCTV140.jpg",
        "city": "Cincinnati",
        "rushHourPriority": true,
    },
    {
        "id": 68,
        "name": "I-75 at South of I-74",
        "url": "https://itscameras.dot.state.oh.us/images/artimis/CCTV093a-L.jpg",
        "city": "Cincinnati",
        "rushHourPriority": true,
    },
    {
        "id": 69,
        "name": "I-71/I-75 at Turfway Rd",
        "url": "http://www.trimarc.org/images/milestone/CCTV_06_75_1823.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 70,
        "name": "I-71/I-75 at Mt. Zion Rd",
        "url": "http://www.trimarc.org/images/milestone/CCTV_06_75_1781.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
    {
        "id": 71,
        "name": "I-71/I-75 at Cut in the Hill",
        "url": "http://www.trimarc.org/images/milestone/CCTV_06_75_1896.jpg",
        "city": "Cincinnati",
        "rushHourPriority": false,
    },
];

module.exports = cameras;